### ISSUE TITLE
SBOLDesigner missing required libraries

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#298]
The problem is simpleeventbus-1.2.jar is not getting pulled in as a dependency for SBOLDesigner.  I also think openrdf-sesame-2.6.9.jar is also missing, but I’m not sure if this is a problem.  Micheal: do you know where this is getting used?  

Essentially, all of the files listed below are dependencies that must be brought in somehow.  These are the ones that do not exist on Maven Central, I believe.  Please double check that each one is being brought in or that you can argue that it is no needed.  One that I’m sure is no longer needed is sbolstack-frontend since this is now part of libSBOLj.  Also, we need to consider how we want to include libsbmlj.jar as it depends on the binary libsbml files as well that are currently missing from our build. Independent of how we deal with reb2sac, this needs to be included somehow.

**Comment by tramyn** [comment]
@michael13162 I modified frontend/pom.xml to get SBOLDesigner working. If you could test SBOLDesginer for your features, this will help guarantee that I got all the dependencies needed in the pom file.

**Comment by cjmyers** [comment]
I got this working but I had a few issues.  One is you misspelled simpleEventBus as simpeEventBus.  It seems to work but confusing.  I also had to manually copy the JAR files into the .m2 directory.  I’m not sure why they were not getting put there.  I also ran mvn clean install, and various other maven commands from eclipse.  I’m not actually sure which combination really did it.  Is there a clear set of steps I should have followed?

**Comment by michael13162** [comment]
Since there's no .classpath anymore, I was initially having a hard time getting iBioSim to even show up in Eclipse.  Thankfully, someone updated the README, but I still had some problems whilst trying to run..
![image](https://cloud.githubusercontent.com/assets/14242505/24713801/e3bc43e0-19e3-11e7-995b-37710291c58c.png)

**Comment by cjmyers** [comment]
The location of the main file has moved.  You likely have it still pointing to the old location.

**Comment by tramyn** [comment]
These issue is resolved. 

For documentation purposes, to resolve errors for new dependencies added to any pom.xml file for iBioSim, make sure to do a mvn clean and maven->update project on iBioSim to ensure the new dependencies are built. This will help resolve the issue that @cjmyers was having. By doing so, there will be no need to manually copy in JAR files to the .m2 directory. 

As for @michael13162's issue, it can be resolved by setting the run configurations to point to the setting shown below. This setting is due to the restructuring the project. The README.md should now mention this step that we forgot to describe for the installation process. 

<img width="653" alt="screen shot 2017-04-05 at 5 28 05 pm" src="https://cloud.githubusercontent.com/assets/7537729/24731174/930229f0-1a25-11e7-9dd4-a1f0225e01a4.png">
