### ISSUE TITLE
Null Exception opening Promoter Editor

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#366]
A Null Exception is thrown when opening the promoter editor for an annotated SBML species. 

Here is the iBioSim project creating this exception.
[sbolAnnot.zip](https://github.com/MyersResearchGroup/iBioSim/files/1062974/sbolAnnot.zip)

**Comment by tramyn** [comment]
Update: testing models that was generated by the VPR model generator  allows me to open the annotated promoter editor without throwing a null exception. It looks like this null exception will consistently occur if I annotate the species with a DNA component manually.

**Comment by cjmyers** [comment]
I cannot reproduce.  Can you give me step-by-step that you do to get this exception.

**Comment by tramyn** [comment]
@cjmyers :
1. create a species in a new SBML model.
2. annotate the species with an SBOL part that has DNA type component taken from the parts registry
3. After associating the SBOL part, the species icon should've turn into a promoter icon. 
4. Double click on the annotated promoter and iBioSim will attempt to pull up the promoter editor. This is where I am getting the NULL pointer exception.

**Comment by cjmyers** [comment]
Ah, this is not a good idea.  We should probably prevent this, since you also need a genetic production reaction.

**Comment by cjmyers** [comment]
Hi Tramy,

I just confirmed this one.  The issue is that it is throwing a null pointer exception when it attempts to find the annotation on the generic production reaction for this “promoter”.  However, there is no such reaction.  These only get created when you drop a “promoter” on the canvas.  

As we discussed yesterday, species and promoters are inherently different as represented in SBML.  A species is represented in SBML as a Species.  However, a promoter is represented in SBML as a Species and a special genetic production Reaction.  Therefore, we have one of two choices at this point:

1) Do not allow a user to annotate a non-promoter species with a DNA type SBOL CD.  Also, do not allow a user to annotate a promoter species with a non-DNA type SBOL CD.  This would likely entail restricting the types in the SBOL edit/registry dialogs, and in addition, double checking the type selected when adding the annotation to prevent a user from adding an invalid CD type.

2) When a non-promoter species is annotated with a DNA type SBOL CD, add the genetic production reaction at the same time (i.e., change it into a promoter species).  When a promoter is annotated with a non-DNA type SBOL CD, remove the genetic production reaction at the same time (i.e., change it into a regular species).

Both approaches would be somewhat involved, however, I think approach (1) is somewhat simpler, and it is likely the right one.  Presumably if the user wants to change the species from promoter to non-promoter or vice versa, it is much cleaner to delete and re-add the species.

Chris

**Comment by cjmyers** [comment]
Also a promoter should not be allowed to be annotated with anything except CDs with type DNA.

**Comment by tramyn** [comment]
Update: This feature has been implemented. If the user decides to annotate an SBML species that is of DNA type, the species will be replaced with a promoter with the annotation attached. 
If the user decides to annotate a promoter that with SBOL component that is not of DNA type then the user will get a warning indicating that this option not allowed and no annotation will take place.
