### ISSUE TITLE
Do not require an output file name for conversion

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#372]
When no output file name is provided for a conversion to SBOL, print the SBOL file to the console just like the validator/converter does.

**Comment by cjmyers** [comment]
Also do not require an output directory for SBOL.  The output directory should be part of the file name, if one is provided.

**Comment by tramyn** [comment]
@cjmyers When performing SBOL2SBML, the user has to provide the output directory and the output file name separately using the command line -oDir and -o because multiple sub models can be created from conversion.
Whereas when calling SBML2SBOL, you want the user to provide the full output file with its path when -o is used and not -oDir and -o?

Do you want the user to provide the full output file name with its path when they perform SBML2SBOL conversion and for the SBOL2SBML conversion, the user has to provide the output directory and

**Comment by cjmyers** [comment]
I think for SBML2SBOL, an output directory is not needed, since it can be provided in the output file name.  So, it should be optional.

For SBOL2SBML, an output directory may be needed if it is converted into more than one file, but it could default to the current directory OR better the directory of the output file.

In either case, no output file provided, should print to console the results.

**Comment by tramyn** [comment]
Update: The current commit should reflect this description.

**Comment by cjmyers** [comment]
Looks good. Closing.
