### ISSUE TITLE
Unable to open SBOLDesigner when selecting multiple designs at once.

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#388]
If I were to select individual designs from the SBOL input dialog and tried open them in SBOLDesigner, no error was thrown. However, if I tried selecting multiple SBOL designs and select open in SBOLDesigner, the following error was thrown.

<img width="968" alt="sboldesigner_err" src="https://user-images.githubusercontent.com/7537729/28554823-f72cd558-70b8-11e7-80db-aa4eccb0dab3.png">

**Comment by cjmyers** [comment]
In the code below, createCopy(SBOLDocument) assumes everything being copied is new.  Therefore, it is not safe to use here, since you end up copying the same object in more than once.  Instead, you need to iterate over all the topLevels returned, check if they are new, and only copy if it does not already exist.  Ideally, you should also check if it does already exist that they are identical.

You might also log a request to the libSBOLj tracker for the createCopy method to do this in the future, but for now, you will need to manage it yourself.

=================
SBOLInputDialog.java
=================
	public SBOLDocument getSelection() {
		try 
		{
			SBOLDocument outputDoc = new SBOLDocument();
			
			for(int r : table.getSelectedRows())
			{
				int row = table.convertRowIndexToModel(r);
				TopLevel comp = ((TopLevelTableModel) table.getModel()).getElement(row); 
				outputDoc.setDefaultURIprefix(comp.getDocument().getDefaultURIprefix());
				outputDoc.createCopy(sbolDesigns.createRecursiveCopy(comp));
			}
			
			return outputDoc;
		} 
		catch (SBOLValidationException e) 
		{
			JOptionPane.showMessageDialog(null, "This TopLevel SBOL object cannot be imported: " + e.getMessage());
			e.printStackTrace();
			return null;
		}
	}

**Comment by cjmyers** [comment]
In the code below, createCopy(SBOLDocument) assumes everything being copied is new.  Therefore, it is not safe to use here, since you end up copying the same object in more than once.  Instead, you need to iterate over all the topLevels returned, check if they are new, and only copy if it does not already exist.  Ideally, you should also check if it does already exist that they are identical.

You might also log a request to the libSBOLj tracker for the createCopy method to do this in the future, but for now, you will need to manage it yourself.

=================
SBOLInputDialog.java
=================
	public SBOLDocument getSelection() {
		try 
		{
			SBOLDocument outputDoc = new SBOLDocument();
			
			for(int r : table.getSelectedRows())
			{
				int row = table.convertRowIndexToModel(r);
				TopLevel comp = ((TopLevelTableModel) table.getModel()).getElement(row); 
				outputDoc.setDefaultURIprefix(comp.getDocument().getDefaultURIprefix());
				outputDoc.createCopy(sbolDesigns.createRecursiveCopy(comp));
			}
			
			return outputDoc;
		} 
		catch (SBOLValidationException e) 
		{
			JOptionPane.showMessageDialog(null, "This TopLevel SBOL object cannot be imported: " + e.getMessage());
			e.printStackTrace();
			return null;
		}
	}

**Comment by tramyn** [comment]
This is fixed and has been tested.
