### ISSUE TITLE
Spaces in project path causes problem with execution with reb2sac/GeneNet

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#408]
When there are spaces in the project path, the execution of reb2sac/GeneNet will does not work.  Need to add quotes around the file name.

**Comment by leandrohw** [comment]
Need to test this. Adding quotes cause problems because the quotes are added as part of the value passed to the process. Previously, commands were created by concatenating strings to form the entire command. I changed this so now it takes an array of strings such that processes can differentiate the arguments properly.

**Comment by tramyn** [comment]
I tested with a path that contained space and it worked.
